name: Deployment to ECS
on:
  push:
    branches:
      - main
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Get build ID
      id: getbuildid
      run: echo "build_id=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry: ${{ secrets.ECR_REGISTRY }}
        region: ${{ secrets.AWS_REGION }}

    - name: Build and Push Docker Image
      run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.AWS_ECR_REPOSITORY }}:${{ steps.getbuildid.outputs.build_id }} .
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.AWS_ECR_REPOSITORY }}:${{ steps.getbuildid.outputs.build_id }}